---
title: "HW3_Q2"
author: "Gabe Abreu"
date: "3/14/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(plotly)
library(shiny)
knitr::opts_chunk$set(echo = TRUE)
```

## Question 2:

Often you are asked whether particular States are improving their mortality rates (per cause)
faster than, or slower than, the national average. Create a visualization that lets your clients
see this for themselves for one cause of death at the time. Keep in mind that the national
average should be weighted by the national population.

```{r}

cdc_df2 <- read.csv('https://raw.githubusercontent.com/charleyferrari/CUNY_DATA_608/master/module3/data/cleaned-cdc-mortality-1999-2010-2.csv')

```


```{r}
cdc_df2 <- cdc_df2 %>% group_by(ICD.Chapter, Year) %>% mutate(Nat.Avg = sum(Deaths)/sum(Population) * 10^5)

```


```{r}
ui <- fluidPage(
  headerPanel('National Average vs State Mortality Rate per Selected ICD'),
  
  
  sidebarPanel(
    selectInput('icd', 'ICD Chapter', unique(cdc_df$ICD.Chapter), selected = 'Neoplasms'),
    selectInput('state', 'State', unique(cdc_df$State),selected = 'CT')
  ),
  
  
  mainPanel(
    plotOutput('plot1')
  )
)


server <- function(input, output) {
  
  output$plot1 <- renderPlot({
    
    
    dfSlice <- cdc_df2 %>% filter(ICD.Chapter == input$icd, State == input$state)

  
 plot_ly(dfSlice, x = ~Year, y = ~Crude.Rate, type = "scatter",  name = input$state, mode = "markers", source = "subset") %>%
        layout(
               xaxis = list(title = 'Year'),
               yaxis = list(title = 'Deaths'),
               plot_bgcolor = "white")%>%
        add_trace(y = ~dfSlice$Nat.Avg, name = 'National Average',mode = 'markers')
  })
  
  
}

shinyApp(ui = ui, server = server)

```