---
title: "Final Project Proposal"
author: "Gabe Abreu"
date: "3/28/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Investigating the Rise of Hate Crimes in the United States

## Background

The Trump administration in many ways was a polarizing administration. The stark divide between political parties and their ideologies became very apparent during Trump's presidency. The Trump administration saw the rise of the BLM movement, white nationalism, ultra right wing conspiracy theories, racial violence, protests, etc. The purpose of my final project is to investigate the recorded hate crimes and see if there was a rise in reported hate crimes during the Trump presidency. 

I want to answer some of the following questions:
Who were the primary offenders? Who were the primary victims? In what area/locations in the United States did these crimes occur? What were the major offenses committed? 

## Data

The primary data source is the FBI(https://ucr.fbi.gov/hate-crime/), they release hate crime data every November, so the latest data they have is from 2019. The 2020 data will not be released until November 2021, which would have been ideal to acquire since it was the election year. However, I can still download and investigate the years from 2016-2019 and go through the various tables. 

Other source of condensed hate crime data:
https://crime-data-explorer.fr.cloud.gov/downloads-and-docs

## Technology

I plan on creating a web app to present the data. So that either means a dash app deployed with heroku with plotly or a shiny app and R. I haven't decided on the approach yet since we're still learning visualization technologies and want to explore a bit more before deciding. 



