---
title: "Final Project"
author: "Devin Teran, Gabe Abreu, Amit Kapoor, Subhalaxmi Rout"
date: "4/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE}
library(twitteR)
library(quantmod)
library(rvest)
library(stringr)
library(purrr)
library(tidytext)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(RCurl)
```



```{r get_urls}
base_url <- 'https://www.whitehouse.gov/briefings-statements/remarks-president-trump-vice-president-pence-members-coronavirus-task-force-press-briefing-'

getPageURLs <- function(url) {
   add_number <- seq(2,33)
   urls <- str_c(base_url, add_number)
   return(urls)
}

urls <- getPageURLs(urls)
```

```{r get-data}
wh_briefings <- purrr::map(urls, ~read_html(.x) %>% html_nodes("p") %>% html_text())
wh_dates <- purrr::map(urls, ~read_html(.x) %>% html_nodes("p") %>% html_node("time") %>% html_text())
 
```


```{r clean-dates}
testFrame <- data.frame(date = character(),
                        stringsAsFactors = FALSE)


for (i in 1:length(wh_dates)){
  testFrame <- rbind(testFrame,cbind(as.data.frame(unlist(wh_dates[[i]]),stringsAsFactors = FALSE),i))
}

dateFrame <- na.omit(testFrame)

```

```{r list-to-dataframe}
data0 <- data.frame(text=character(),
                   Day=integer(),
                 stringsAsFactors=FALSE)

for (i in 1:length(wh_briefings)){
  data0 <- rbind(data0,cbind(as.data.frame(unlist(wh_briefings[[i]]),stringsAsFactors = FALSE),i))
}

colnames(data0) <- c('text','day')
```

```{r}

correctMatch <- inner_join(dateFrame,data0,by= c("i" = "day"))
colnames(correctMatch) <- c('date', 'day', 'text')

data <- correctMatch

```

```{r create-stop-word-list}
custom_stop_words <- bind_rows(tibble(word = c("EDT"), 
                                      lexicon = c("custom")), 
                               stop_words)

custom_stop_words
```
```{r clean-data}
tidy_data <- data %>%
  mutate(linenumber = row_number()) %>%
  ungroup() %>%
  unnest_tokens(word, text)
```



```{r apply lexicon analysis}
afinn <- get_sentiments("afinn") 

tidy_data %>%
  anti_join(stop_words) %>%
  group_by(day) %>%
  inner_join(afinn) %>%
  count(word, sort = TRUE) %>%
  arrange(day,-n)
```

### Sentiment Analysis

```{r affin, echo=TRUE, warning=FALSE}

# Using lexicon affin
affinLex <- get_sentiments("afinn")
wh.affin <- tidy_data %>% 
  anti_join(stop_words) %>% 
  group_by(day) %>%
  inner_join(affinLex) %>% 
  summarise(sentiment = sum(value)) %>% 
  mutate(method="affin")

wh.affin
```


```{r affin-bar, echo=TRUE, warning=FALSE}

# bar plot for positive and negative cumulative score
wh.affin %>% 
  summarise(Positive = sum(sentiment[sentiment>0]), Negative = sum(sentiment[sentiment<0])) %>% 
  gather(variable, value, Positive:Negative) %>% 
  ggplot(aes(variable, value,  fill = variable)) +
  geom_bar(stat="identity") +  
  geom_text(aes(label=value), position=position_dodge(width=0.9), vjust=-0.25)
```




```{r bing, echo=TRUE, warning=FALSE}

# Using lexicon bing 

bingLex <- get_sentiments("bing")
wh.bing <- tidy_data %>% 
  anti_join(stop_words) %>% 
  group_by(day) %>%
  inner_join(bingLex) %>% 
  count(day, sentiment) %>% 
  spread(sentiment, n, fill=0) %>% 
  mutate(sentiment = positive - negative) %>%
  mutate(method="bing")

wh.bing
```

  


  
```{r bing-bar, echo=TRUE, warning=FALSE}

# bar plot for positive and negative sentiments
wh.bing %>% 
  ungroup() %>%
  select(-day) %>% 
  select(negative, positive) %>% 
  summarise_all(funs(sum)) %>% 
  gather(variable, value, negative:positive) %>% 
  ggplot(aes(variable, value,  fill = variable)) +
  geom_bar(stat="identity") +  
  geom_text(aes(label=value), position=position_dodge(width=0.9), vjust=-0.25)

```




```{r nrc, echo=TRUE, warning=FALSE}

# Using lexicon nrc

nrcLex <- get_sentiments("nrc")
wh.nrc <- tidy_data %>% 
  anti_join(stop_words) %>% 
  group_by(day) %>%
  inner_join(nrcLex) %>% 
  filter(sentiment %in% c("positive", "negative")) %>%
  count(day, sentiment) %>% 
  spread(sentiment, n, fill=0) %>% 
  mutate(sentiment = positive - negative) %>%
  mutate(method="nrc")

wh.nrc
```

  
```{r nrc-bar, echo=TRUE, warning=FALSE}

# bar graph for all sentiment categories in nrc lexicon
tidy_data %>% 
  anti_join(stop_words) %>% 
  group_by(day) %>%
  inner_join(nrcLex) %>% 
  #filter(sentiment %in% c("positive", "negative")) %>%
  count(day, sentiment) %>% 
  spread(sentiment, n, fill=0) %>% 
  ungroup() %>%
  select(-day) %>% 
  summarise_all(funs(sum)) %>% 
  gather(variable, value, anger:trust) %>% 
  ggplot(aes(variable, value,  fill = variable)) +
  geom_bar(stat="identity") +  
  geom_text(aes(label=value), position=position_dodge(width=0.9), vjust=-0.25)

```




```{r plot-all-lex, echo=TRUE, warning=FALSE}

# Comparing all 3 lexicons

wh.aff_bin_nrc <- bind_rows(wh.affin, wh.bing, wh.nrc)
bind_rows(wh.aff_bin_nrc) %>%
  ggplot(aes(day, sentiment, fill = method)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~method, ncol = 1, scales = "free_y")
```



```{r compare-all-lex, echo=TRUE, warning=FALSE}

# comparing the cumulative sentiments for all 3 lexicons
wh.aff_bin_nrc %>% 
  group_by(method) %>% 
  summarise(sentiment = sum(sentiment)) %>% 
  ggplot(aes(method, sentiment, fill = method)) +
  geom_bar(stat="identity") +  
  geom_text(aes(label=sentiment), position=position_dodge(width=0.9), vjust=-0.25)
```



```{r plot-line-all, echo=TRUE, warning=FALSE}

# line graph for all 3 lexicons
wh.aff_bin_nrc %>% 
  ggplot(aes(x=day, y=sentiment, group=method, color=method)) + 
  geom_line(size=1) + 
  geom_point() + labs(x="day", y="sentiment", title = "Sentiment vs Days for all 3 lexicons") + 
  scale_color_manual(values=c("red", "green", "blue"))
```



** Stock Market Data

```{r}

start<- as.Date("2020-03-15")
end <- as.Date("2020-04-27")


#Retrieving information on Top 5 Small Growth Funds as ranked by "U.S. News"
smallCapFunds <- c("PSGAX", "FKASX", "PGSGX", "QUASX", "TRSSX")
getSymbols(smallCapFunds, src = "yahoo", from = start, to = end)

#Retreiving information on Top 5 Mid Growth Funds as ranked by "U.S. News"
midCapFunds <- c("DFDMX", "CCSMX","PRDMX", "OTCAX", "BMGAX")
getSymbols(midCapFunds, src = "yahoo", from = start, to = end)

#Retrieving information on Top 5 Large Growth Funds as ranked by "U.s News"
largeCapFunds <- c("TRLGX", "PREFX", "TPLGX", "FDSVX", "PBLAX")
getSymbols(largeCapFunds, src = "yahoo", from = start, to = end)


#Retrieve Dow Jones Industrial Average
getSymbols("DJIA", src = "yahoo", from = start, to = end)

```


### Datasource :: Trump approval rating: https://projects.fivethirtyeight.com/trump-approval-ratings/

```{r trump-appr, echo=TRUE, warning=FALSE}

#github URL
theURL <- getURL("https://raw.githubusercontent.com/geeman1209/MSDATA2020/master/DATA607/Final_Project/approval_topline.csv")
# Read csv from github
trump_apprdf <- read.csv(text = theURL,stringsAsFactors = FALSE)
# glimpse data
dplyr::glimpse(trump_apprdf)

```


```{r date, echo=TRUE, warning=FALSE}

# modeldate - convert into date
trump_apprdf$modeldate <- mdy(trump_apprdf$modeldate)
dplyr::glimpse(trump_apprdf)
```

```{r filter-apr, echo=TRUE, warning=FALSE}

# filter data for April , 2020
trump_apprsubdf <- trump_apprdf %>% 
  filter(modeldate >= as.Date("2020-04-01"))
```


```{r approval-bar, echo=TRUE, warning=FALSE}

# Approval bar plot for all 3 sub groups  
ggplot(trump_apprsubdf, aes(x=modeldate,y=approve_estimate,fill=subgroup)) +
  geom_bar(stat="identity", position = 'dodge') +
  xlab('Date') +
  ylab('Approval estimates') + 
  ggtitle('Trump approval estimates for April 2020') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 90)) 
```


```{r approval-line, echo=TRUE, warning=FALSE}

# Approval line plot for all 3 sub groups  
trump_apprsubdf %>% 
  ggplot(aes(x=modeldate,y=approve_estimate, group=subgroup, color=subgroup)) + 
  geom_line(size=1) + 
  geom_point() + labs(x="Date", y="Approval estimates", title = "") + 
  scale_color_manual(values=c("red", "green", "blue"))
```

```{r disapproval-bar, echo=TRUE, warning=FALSE}

# Disapproval bar plot for all 3 sub groups  
ggplot(trump_apprsubdf, aes(x=modeldate,y=disapprove_estimate,fill=subgroup)) +
  geom_bar(stat="identity", position = 'dodge') +
  xlab('Date') +
  ylab('Disapproval estimates') + 
  ggtitle('Trump disapproval estimates for April 2020') +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 90)) 
```


```{r disapproval-line, echo=TRUE, warning=FALSE}

# Disapproval line plot for all 3 sub groups 
trump_apprsubdf %>% 
  ggplot(aes(x=modeldate, y=disapprove_estimate, group=subgroup, color=subgroup)) + 
  geom_line(size=1) + 
  geom_point() + labs(x="Date", y="Disapproval estimates", title = "") + 
  scale_color_manual(values=c("red", "green", "blue"))
```




#Resource:  
  
* [https://bradleyboehmke.github.io/2015/12/scraping-html-text.html](https://bradleyboehmke.github.io/2015/12/scraping-html-text.html)  
* [Automated Data Collection PDF Book](Automated Data Collection PDF Book)
